apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-onprem
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:KristijanBoshev/interoperable-portable-agnostic-stack.git
    targetRevision: HEAD
    path: k8s/overlays/onprem
  destination:
    server: https://kubernetes.default.svc
    namespace: todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
