apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-api
  labels:
    app.kubernetes.io/name: todo-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
    traefik.ingress.kubernetes.io/service.request-headers: X-Forwarded-Proto:https
spec:
  ingressClassName: traefik
  rules:
    - host: todo.kristijanboshev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-api
                port:
                  number: 80
