apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-onprem.yaml

images:
  - name: todo-api
    newName: ghcr.io/kristijanboshev/interoperable-portable-agnostic-stack
    newTag: v1.0.0
