apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: todo-api
  labels:
    app.kubernetes.io/name: todo-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-api
